name: CI Build

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/android.yml
    with:
      gradle-task: "assembleDebug"
      upload-artifact: true
      artifact-name: app-debug
      artifact-path: app/build/outputs/apk/debug/*.apk
